### ISSUE TITLE
gRPC traffic via explicit proxy is not captured when https is used (works with http)

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/fiddler-everywhere#13]
**Describe the bug**
Set the fiddler proxy (http**s**://127.0.0.1:8866) to your gRPC app.
Traffic goes through (the app works), but nothing is shown in Fiddler.
I would not really expect to work, although I have trusted the Fiddler cert, so it does make sense that it does, but this maybe should vary depending on the cert status.
When you change it to http://127.0.0.1:8866 the app keeps working and traffic shows in Fiddler.

**To Reproduce**
1. Go to your gRPC app and give it Fiddler's proxy
2. use the "https" protocol
3. generate traffic

**Expected behavior**
You see the traffic even when https schema is used
If it is not supposed to work (as in - Fiddler does not listen on https), I expect no traffic goes through so my app does not get network and does not work.

**Comment by marin-bratanov** [comment]
forgot to mention, I am now on 5.8.1, I do not remember if it was different in older versions.

**Comment by NickIliev** [comment]
@marin-bratanov This is a design decision from the early days of Fiddler - historically, the Fiddler proxy has never supported https as a protocol for the proxy tunnels (protocol for proxying). As Fiddler is meant to be used as a local forward proxy, we use only HTTP for tunnels (CONNECT Tunnel sessions).

Another reason why the team is hesitant to provide support for https (as a proxy protocol) is that there is limited support from many client applications, and most of them are still supporting only the known HTTP protocol format (e.g., `http=127.0.0.1:8866;https=127.0.0.1:8866,` but limited support for `http=https://127.0.0.1:8899;https=https://127.0.0.1:8899;`)
