### ISSUE TITLE
gRPC client request messages have a wrong arrow (like a server response)

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/fiddler-everywhere#14]
**Describe the bug**
The downwards pointing green arrow indicates (at least to me, but I think it should be generally valid) a successful server response in the message.
It is also used for outgoing client request messages, which is confusing.
For client messages I expect the arrow to point upwards ("towards the server").

**To Reproduce**
1. Capture gRPC traffic
2. Get the protobuf in and capture a client request (in my example it is a search with a string like 'pppppp' to indicate there needs to be date sent to the server to show what the client wants from the server and it is not in the URL)
3. Examine the Messages tab
4. All arrows point down like server responses which is incorrect and confusing

**Expected behavior**
upwards arrows for requests, downwards arrows for responses; green for success, red for errors.

**Screenshots**
![2024-04-16 14_36_44-Fiddler Everywhere](https://github.com/telerik/fiddler-everywhere/assets/5746515/937881d1-ef69-4d94-b582-9949d3a4dcc0)

**Comment by NickIliev** [comment]
Hey @marin-bratanov, thanks for reporting this one. I can confirm that there is a bug in the UI presentation of the gRPC messages, as currently most of them are marked with a green downward arrow (Server).

**Comment by NickIliev** [comment]
Fixed in the latest version of Fiddler Everywhere
