### ISSUE TITLE
Help Needed: Locating Custom Rules and Scripts in the Latest Version of Fiddler Everywhere

### ISSUE THREAD

**Issue by Aaron009** [telerik/fiddler-everywhere#19]
Hi everyone,

I recently updated to the latest version of Fiddler Everywhere and I'm having some trouble finding where to customize rules and scripts. In previous versions, there was a clear option for this, but I seem to be missing it now.

Could someone guide me on how to access these features in the newest update? Any help or pointers towards the right menu or settings would be greatly appreciated!

Thank you in advance!

I'm in the latest version of Fiddler Everywhere, which lacks custom rules and custom scripts.

**Comment by NickIliev** [comment]
Hey @Aaron009 

The Fiddler Everywhere application introduced the **Rules** tab, which enables you to create custom rules to tackle various tasks, such as mapping and modifying traffic, debugging through breakpoints, creating block and allow lists, filtering, and modifying UI.

Learn more about the feature from the following documentation links:

https://docs.telerik.com/fiddler-everywhere/modify-and-filter-traffic/modify-traffic-with-rules 

https://docs.telerik.com/fiddler-everywhere/modify-and-filter-traffic/breakpoints

You can also utilize the following rule presets to quickly understand how to create and apply different conditions and actions for various tasks.

https://docs.telerik.com/fiddler-everywhere/rules-presets/rules-presets

**Comment by Aaron009** [comment]
Dear Fiddler Team,

I hope this message finds you well.

I am a dedicated user of Fiddler and would like to express my gratitude for your continuous efforts to improve and enhance this powerful tool. Fiddler has become an indispensable asset for network debugging and analysis, thanks to its robust functionality and user-friendly interface. However, I would like to take this opportunity to suggest some improvements that could further enhance the user experience and extend the capabilities of Fiddler.

My suggestions are as follows:

1. **Easier Control of Rules via Python or C# Programming:**
   Currently, Fiddler primarily uses custom scripts (e.g., JScript.NET) to control traffic rules. While this approach is flexible, adding support for Python or C# would make writing and managing rules more intuitive and efficient. These languages are widely used in the developer community and offer extensive libraries and tool support, simplifying the implementation and debugging of complex rules.

2. **Support for Breakpoint Debugging:**
   Debugging is crucial for complex traffic interception and modification rules. If Fiddler could provide breakpoint debugging, allowing developers to step through rule execution and inspect variables in real-time, it would significantly enhance development efficiency and reduce debugging time.

I firmly believe that these improvements would make Fiddler even more powerful and user-friendly, benefiting current users and attracting new ones. Thank you once again for providing such an excellent tool, and I appreciate your consideration of my suggestions amidst your busy schedule.

I look forward to Fiddler's continued evolution!

Sincerely
