### ISSUE TITLE
Fiddler Everywhere is slower when Microsoft Defender for Endpoint is installed

### ISSUE THREAD

**Issue by jivkopiskov** [telerik/fiddler-everywhere#3]
**Describe the bug**
Since installing Microsoft Defender and enabling real-time protection, the application is slower than before. It took over 2-3 minutes to install the app, the startup time is much slower and switching between sessions and loading the inspectors seems slower.

Used Operating System: macOS Sonoma
Affected Fiddler Installation time
It affected how fast the application starts
It affected how fast the inspectors load
Affected how long it takes for updates to be installed

**To Reproduce**
Install MS Defender for Endpoint and enable Real-time protection

**Expected behavior**
The app should behave similarly with or without the defender

**Comment by NickIliev** [comment]
Performance improvements were added through several releases.

Additionally, in some cases, the MS Defender administrators need to explicitly whitelist the Fiddler Everywhere applications while using the following commands:

```bash
# speed up app Startup and working
mdatp exclusion folder add --path "Applications/Fiddler Everywhere.app"
# speed up how fast we install it from .dmg
mdatp exclusion folder add --path "/Volumes/Fiddler Everywhere*"
# prevent isuses with auto-update
mdatp exclusion folder add --path "/Users/fiddlerbuilduser/Library/Caches/*fiddler*/"
mdatp exclusion process add --name "ShipIt"
# Additionally, we can also add for more performance
mdatp exclusion process add --name "Fiddler Everywhere"
mdatp exclusion process add --name "Fiddler.WebUi"
```
