### ISSUE TITLE
Chrome spawned by Fiddler crashes after initially viewing any website

### ISSUE THREAD

**Issue by atcuno** [telerik/fiddler-everywhere#35]
**Describe the bug**

My normal workflow of launching Fiddler, using it to launch the clean/intercepted Chrome, and then visiting a website now causes Chrome to freeze every single time after initial page load.

 - Used Operating System: [e.g., macOS Sonoma]

$ sw_vers
ProductName:         macOS
ProductVersion:      14.5
BuildVersion:		23F79

Intel Mac.

Fiddler:

Version: 5.15.1
Built: Tuesday, August 6, 2024
Build Type: Intel (x64)

Chrome:

Version 127.0.6533.120 (Official Build) (x86_64)

 - Affected Fiddler UI [e.g., Login screen, Live Traffic pane, Rules tab, etc.]

Launch browser

 - Affected functionality (HTTPS capturing, gRPC, Browser capturing, WebSockets, etc.)

Simply visiting a website and waiting for page load causes Chrome to crash. Fiddler records the traffic as expected until the crash.

**To Reproduce**

1. Launch Fiddler Everywhere
2. Launch the clean instance browser
3. Visit www.abc.com (or any other website)
4. After the page begins to load, the Chrome instance freezes. This does not happen with the browser outside of Fiddler.

**Expected behavior**
The web page to be usable as in the past.

**Comment by NickIliev** [comment]
Hey @atcuno, we know about certain issues with the latest version of the Chromium engine and some GPU drivers. We are currently working on a fix and plan to release it in the next version of Fiddler Everywhere, which should be ready in approximately one or two weeks.

Meanwhile, as a possible temporary solution, you can try the following:
1. Launch Fiddler Everywhere
2. Go to **Settings > Browser**s and set a folder to persist the data through the **Persist data in specific directory** option
![image](https://github.com/user-attachments/assets/3f8485aa-1caf-4393-a62a-fcb2cb12d701)
3. Visit [www.abc.com](http://www.abc.com/) (or any other website)
4. Restart the Fiddler's clean browser instance after the initial crash

The above should cache specific browser settings, and in some cases, resolve the issue, which appears with a clean instance.

Another possibility that is unrelated to the GPU fix is that you might have a tool like **Microsoft Defender for macOS** that explicitly blocks the Fiddler Everywhere tool and causes performance issues and crashes with the clean instance. If that is the case, then you need to allowlist the Fiddler app through the following commands:

```bash
# speed up app Startup and working
mdatp exclusion folder add --path "Applications/Fiddler Everywhere.app"
# speed up how fast we install it from .dmg
mdatp exclusion folder add --path "/Volumes/Fiddler Everywhere*"
# prevent isuses with auto-update
mdatp exclusion folder add --path "/Users/fiddlerbuilduser/Library/Caches/*fiddler*/"
mdatp exclusion process add --name "ShipIt"
# Additionally, we can also add for more performance
mdatp exclusion process add --name "Fiddler Everywhere"
mdatp exclusion process add --name "Fiddler.WebUi"
```

**Comment by atcuno** [comment]
The new update fixes this.
