### ISSUE TITLE
Add a korean translations

### ISSUE THREAD

**Issue by lunDreame** [telerik/fiddler-everywhere#39]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a translation to Korean

**Describe the solution you'd like**
Can I contribute using a translation site like lokalise

**Additional context**
-

**Comment by NickIliev** [comment]
@lunDreame, Fiddler Everywhere does not yet support the option to add a language pack. We logged this as a public feature request through the following portal thread, which you can upvote to raise its priority.

https://feedback.telerik.com/fiddler-everywhere/1468153-fiddler-everywhere-how-to-set-up-my-country-s-language-i-saw-pak-language-pack-file
