### ISSUE TITLE
Can't start Free Treal

### ISSUE THREAD

**Issue by GalinaS-qa** [telerik/fiddler-everywhere#42]
**Describe the bug**
A clear and concise description of what the bug is. Along with the description, consider providing the following information:

 - Used Operating System: Windows
 - Affected Fiddler UI : Login screen

**To Reproduce**
1. Create an account and login to the app
2. Click on 'Start Free Trial'
3. See error

**Expected behavior**
Free Treal is started. Main screen is opened.

**Screenshots**
![image](https://github.com/user-attachments/assets/03a51002-b76b-49f8-b937-60907492da62)

**Comment by NickIliev** [comment]
The error you received indicates that the trial version is unavailable in your country/region. Please contact us through the [Telerik support center](https://www.telerik.com/account/support-center), if you would like to receive additional details regarding why the limitation occurs for the specific region from which you are trying to use Fiddler Everywhere.
