### ISSUE TITLE
Unable to filter by session type

### ISSUE THREAD

**Issue by xxchien** [telerik/fiddler-everywhere#46]
Filtering by Session Type cannot be found in fiddler, but it is in the official documentation.

![Image](https://github.com/user-attachments/assets/abceae74-f44e-4109-ac47-61e454b24b7d)

https://docs.telerik.com/fiddler-everywhere/modify-and-filter-traffic/conditions-and-actions
![Image](https://github.com/user-attachments/assets/6de09868-ebf2-408f-ab30-57eed9c1be63)

**Comment by NickIliev** [comment]
Indeed, we recently reworked some of our pre-defined columns and removed the Session Type column, as it duplicates values you can obtain from other columns. For example, you can use the Protocol column to obtain the used protocol (like Socket.IO, gRPC, etc.), or you can use the Method column to obtain the type of the used HTTP method (like GET, POST, CONNECT), and, finally, you can use Session State to obtain the current state of each HTTP session.

![Image](https://github.com/user-attachments/assets/6d336c0e-ed49-4fe1-91e6-735f5a71e22c)

Thank you for showing us the discrepancy in the documentation. We will update it according to the recent changes.
