### ISSUE TITLE
Can't sign into Fiddler on web, insecure connection

### ISSUE THREAD

**Issue by markus27183** [telerik/fiddler-everywhere#47]
Can't sign in to Fiddler  

![Image](https://github.com/user-attachments/assets/3a695a64-a1ac-456d-9177-542616bab3e4)

**Comment by NickIliev** [comment]
@markus27183, it seems that you might have another proxy tool that uses an invalid certificate. Can you verify that you are not running any other instances of Fiddler (like FIddler Classic) or similar proxy tools, then restart your browser and retry the login attempt again?

Overall, you can also try the following approaches (with Fiddler Everywhere stopped and then restarted)

```
1. Clear Browser Cache and Cookies
2. Adjust the Time and Date Settings on Your Computer
3. Temporarily Disable Browser Extensions
4. Update Your Browser
5. Clear the SSL State
6. Deactivate VPN
7. Disable Firewall or Antivirus
```
