### ISSUE TITLE
Add global search functionality for multiple Request/Response Bodies

### ISSUE THREAD

**Issue by SvetlaGeorgieva** [telerik/fiddler-everywhere#5]
**Is your feature request related to a problem? Please describe.**

Some users have reported difficulty finding specific sessions in the already captured sessions based on information that is contained within the HTTP bodies.

**Describe the solution you'd like**

Consider extending the global search functionality to support searching in Request/Response Bodies in multiple sessions.

**Comment by NickIliev** [comment]
Currently, Fiddler Everywhere does have [a global quick search](https://docs.telerik.com/fiddler-everywhere/knowledge-base/live-traffic-pane#searching) that matches specific terms from the session's grid or the specific session HTTP headers. Search that can match specific terms from multiple HTTP Bodies would need to be more efficient in terms of performance (e.g., searching in thousands of bodies with sizes varying from a few KB to many MB). 

The above said, having a global search that searches within multiple HTTP bodies is **a no-go** at this point as it can cause performance issues when working with larger volumes of incoming live traffic data.


**Solution**

The Fiddler Everywhere app provides filtering traffic through [enhanced filtering options.](https://docs.telerik.com/fiddler-everywhere/modify-and-filter-traffic/filter-traffic). That enables users to create a filtering rule based on a matching condition that looks for a specific value within the HTTP Request and Response Bodies.

For example
![image](https://github.com/telerik/fiddler-everywhere/assets/18008302/65c8e0a1-b7b5-4e21-b48a-e5c5b47d20db)

**Comment by NickIliev** [comment]
The latest version of Fiddler Everywhere can now be searched within the Request and Response bodies. The new feature can be turned on by toggling the "Search in Body" option in the Quick Search field.

![image](https://github.com/telerik/fiddler-everywhere/assets/18008302/d20e38c4-251c-47e0-a418-a2ea74ef42b8)


More details about the feature are available here:
https://docs.telerik.com/fiddler-everywhere/knowledge-base/live-traffic-pane#searching-within-request-and-response-bodies
