### ISSUE TITLE
Stop asking me to upgrade

### ISSUE THREAD

**Issue by jeremy-schaab** [telerik/fiddler-everywhere#50]
There is nothing more annoying than having to pay for something that used to be free, especially when I already have the full Dev Craft Kit.  It's like that annoying thing you are doing with the theme builder, just make the Dev Craft Complete, actually complete.  But most importantly, stop asking me for money or to upgrade when I already paid, it's obnoxious.

**Comment by endarova** [comment]
Hi jeremy-schaab,

Thank you for reaching out and sharing your feedback. I understand how frustrating it can feel to encounter upgrade prompts, so I’d like to take this opportunity to clarify the situation and ensure all your questions are addressed.
You're seeing the upgrade messages, as you’re currently subscribed to the Fiddler Everywhere Lite plan. The messages are designed to inform you about additional features available in our higher-tier plans, should you need them in the future. 
We appreciate your support as a valued customer, and it’s never our intention to cause any inconvenience. Our goal is to provide flexible options, allowing you to choose the tools and functionality that best fit your workflow and budget.

If you have further questions or if there’s anything we can assist you with, please don’t hesitate to reach out.
