### ISSUE TITLE
Failed to log in - Backend login failed

### ISSUE THREAD

**Issue by JaieParker** [telerik/fiddler-everywhere#6]
**Describe the bug**
Fiddler everywhere consistently fails to login.

One reason is because your OAuth is not letting me select which account I should log in via and I have 2 valid accounts, a personal account which has Fiddler everywhere and a business account which does not.

**To Reproduce**
1. Sign into an account which is registered with Telerik which does not have fiddler everwhere
2. Open fiddler everywhere and click sign
3. It does not allow me to select an account to sign in with and assume you have the right account and gives this error
4. 
![image](https://github.com/telerik/fiddler-everywhere/assets/6509093/20f666b4-68a0-46a0-b362-98ccfa92461e)

`Something Went WrongBackend login failed.
Make sure you have access to the following APIs:
https://*.telerik.com
https://*.getfiddler.com
https://fiddler-backend-production.s3-accelerate.amazonaws.com
Need more help or interested in using Fiddler offline?[ Contact us here.](mailto:support@getfiddler.com)`

**Expected behavior**
When it works out I dont have the product provide an option to sign in with another account which does so I dont have to sign out of everything

The second issue is I am unable to log in with my normal account either, which does have an active subscription Aug 28, 2024, I get the same error and I have re-installed to latest version 
I just get the same error.

I can reach all the sites listed
When visiting https://fiddler-backend-production.s3-accelerate.amazonaws.com
I get:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B2ZNX5W6RQ32TADZ</RequestId>
<HostId>/0y0l8k8g6+H/xg7QSV06WY1e6K5lDayn+LGmc5u9RcWT++Ubt6jxBwIJ/beZKkmlAH5yb17KCQ=</HostId>
</Error>
```

Help please as I wish to use your product

**Comment by NickIliev** [comment]
The observed error **"Backend login failed"** is unrelated to using multiple accounts in Telerik. It appears that your device has limited access to some of the required endpoints. Note that even if you can open these endpoints through a browser, that does not guarantee that your system can access them through another application (like the Fiddler Everywhere application, which uses Electron).

To test if you can reach the endpoints (from another application apart from browsers), you can execute the following from a terminal.

```bash
curl -v https://api.getfiddler.com/versions
```
If you are experiencing issues with logging in, you can check the Fiddler log files for possible errors. You can access the log files by following the steps outlined in [this knowledge base article](https://docs.telerik.com/fiddler-everywhere/knowledge-base/accessing-fiddler-logs#accessing-the-logs-manually) or by selecting the "**Help**" option and then choosing "**Open Application Logs Folder**". It's best to consult your system or network administrator and request to allowlist the endpoints mentioned above. 

In case you are unable to resolve the issue, forward the application log files privately to our [official support center](https://www.telerik.com/account/support-center). Do not post the logs publicly as they may contain personal and sensitive information. 

The above said, the Fiddler license is connected to your Telerik account, you will need to sign out from the Telerik.com and sign in with the account that holds your Fiddler license. Once you are able to successfully login, you can easily switch between different accounts within the Fiddler Everywhere application while using the **Sign Out** option. 
![image](https://github.com/telerik/fiddler-everywhere/assets/18008302/12d469c9-0109-423f-aa12-3e2612ee3ca7)
