### ISSUE TITLE
Trust Certificate can't enabled the https 

### ISSUE THREAD

**Issue by chriskimx** [telerik/fiddler-everywhere#7]
**Describe the bug**
I clicked the Enabled HTTPS button and nothing happened
 - .Used Operating System: Windows 11
 - Affected Fiddler UI: Trust Certificate and Enabled HTTPS windows
 - Affected functionality : HTTPS can't capture or view

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Enable HTTPS now.....' link
3. Go to 'TRUST AND ENABLED HTTPS'
4. See error: Keep iddlle

**Expected behavior**
Completed the enabled HTTPS and should display "HTTPS" on the LIVE Traffic screen

**Screenshots**
![Screenshot 2024-03-08 185007](https://github.com/telerik/fiddler-everywhere/assets/149546356/7f9ee3fc-c100-4e93-9d88-2505a015316d)

**Additional context**

**Comment by lovets92** [comment]
I can't see HTTPS traffic after updating to macOS 14.4

* Fiddler Everywhere v5.6.0
* MacBook m2 pro - macOS 14.4 
* Pixel 5a - Android 14 
* iPhone 13 - iOS 17.4
![2024-03-10 12 43 50](https://github.com/telerik/fiddler-everywhere/assets/162902023/d2954aa7-cbe9-467e-be01-732735f87ffd)
![2024-03-10 12 43 53](https://github.com/telerik/fiddler-everywhere/assets/162902023/fed27083-4c47-49f1-9a8c-437d34bfe826)

**Comment by NickIliev** [comment]
@chriskimx in your case, you must explicitly accept the FIddler CA installation through the native Windows dialog that shows underneath the Fiddler application. You can invoke the native Windows dialog from the Windows taskbar.

![image](https://github.com/telerik/fiddler-everywhere/assets/18008302/1f27f610-9749-4830-b7c2-a40f28c8c671)


@lovets92 you are experiencing an issue related to a bug in the latest version of macOS Sonoma 14.4. Our team is currently working on a hotfix, and you can track the progress of the issue on the following GitHub thread.

https://github.com/telerik/fiddler-everywhere/issues/9
