### ISSUE TITLE
Remember state of "Toggle Word Wrap"

### ISSUE THREAD

**Issue by RaptorCZ** [telerik/fiddler-everywhere#8]
Toggle Word Wrap feature keeps resettting. Remember the last state to make it more user friendly.
![image](https://github.com/telerik/fiddler-everywhere/assets/4438783/621db1de-b830-4ef4-9643-c2a5faf74062)

**Comment by rosen-vladimirov** [comment]
Hey @RaptorCZ ,
Can you please elaborate more for the scenarios where the value is reset? Is it when switching between different sessions or when you resetart the app? If it is between sessions, what is the type of sessions you are inspecting - are they websockets, Server-sent events or just some HTTP requests

**Comment by RaptorCZ** [comment]
I found 3 scenarions when it happens:
1. on app restart
2. when switched from/to "body" tab on request/response inspectors
3. switching rows in traffic view using double click (it switches to body tab)

It is so many clicks to keep it in "unwrap state". App should respect my selection and stop switching to "wrap".

**Comment by NickIliev** [comment]
@RaptorCZ With [Fiddler Everywhere version 5.9.0](https://www.telerik.com/support/whats-new/fiddler-everywhere/release-history/fiddler-everywhere-v5.9.0), we fixed several issues, including preserving the word-wrap state in different Fiddler Everywhere instances.
