### ISSUE TITLE
Fiddler can't capture HTTPS on macOS Sonoma 14.4 (ERR_SSL_PROTOCOL_ERROR)

### ISSUE THREAD

**Issue by NickIliev** [telerik/fiddler-everywhere#9]
**Describe the bug**
A clear and concise description of what the bug is. Along with the description, consider providing the following information:

 - Used Operating System: **macOS Sonoma 14.4**
 - Affected functionality: **HTTPS capturing**

**To Reproduce**
1. Install macOS Sonoma 14.4
2. Install Fiddler Everywhere 5.6.0
3. Install and trust the Fiddler CA
4. Try to capture any HTTPS traffic

As a result, Fiddler can't complete the TLS handshake and shows only the CONNECT Tunnels (443) requests. The failed connections will return something like **ERR_SSL_PROTOCOL_ERROR** in client applications.

**Expected behavior**
Fiddler to capture HTTPS with macOS Sonoma 14.4 and newer.

**Additional context**
The issue relates to a compatibility bug within the released version of macOS Sonoma and some .NET APIs used by Fiddler. The latest macOS Sonoma version breaks the usage of a known .NET API.

reported through:
https://github.com/telerik/fiddler-everywhere/issues/7#issuecomment-1987273646
t1644313
t1644322
t1644298

**Comment by lovets92** [comment]
It's work on 5.7.0! Thanks!
